CLASS_NAMES = {
    0: "background",
    1: "avalanche",
    2: "building_undamaged",
    3: "building_damaged",
    4: "cracks/fissure/subsidence",
    5: "debris/mud//rock flow",
    6: "fire/flare",
    7: "flood/water/river/sea",
    8: "ice_jam_flow",
    9: "lava_flow",
    10: "person",
    11: "pyroclastic_flow",
    12: "road/railway/bridge",
    13: "vehicle",
}
